[package]
name = "rusty_themy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightningcss = { version = "1.0.0-alpha.40", features = ["visitor"] }
cssparser = "0.29.6"